apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
type: Opaque
stringData:
    api-key: Your Cloudflare api key goes here for auto tls cert management
    email: used to cert manager for Lets encrypt