apiVersion: v1
kind: Secret
metadata:
    name: harbor-pull
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: -.*,traefik
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: Harbor robot account comes here
