# Cluster-wide secrets: harbor-pull, cloudflare-api, minio-secret.
# Decrypted via sops-gpg.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./secrets/5-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
