apiVersion: v1
kind: Namespace
metadata:
  name: reflector
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  targetNamespace: reflector
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: reflector
      version: "9.x"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  values:
    nodeSelector:
      workload: infrastructure
