---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-stack.yaml
  - loki.yaml
  - promtail.yaml
  - tempo.yaml
  # - opentelemetry-collector.yaml
